### Constants
@host=192.168.1.34
@user=admin
@password=admin
@port=8111
@superUserToken=8725108444761557112

### Hardcoded data
@projectId=project10
@buildTypeId= buildType10

### GET all projects
//GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects/name:test_0CeXMseNlR
// all prpjects with the given criteria
GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects?locator=name:5
//GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects?locator=name:contains(test)
//GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects?locator=name:startsWith(test)
//GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects?locator=name:contains(roe)
Content-Type: application/json
Accept: application/json

### Step 1: Create Project
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects
Content-Type: application/json
Accept: application/json

{
    "parentProject": {
        "locator": "_Root"
    },
    "name": "{{projectId}}",
    "id": "{{projectId}}",
    "copyAllAssociatedSettings": true
}

### Search
http://192.168.1.34:8111/admin/admin.html?keyword=ddd&submitFilter=Filter&includeArchived=true&_includeArchived=&item=projects